import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { BASELINE_HEADERS, menuCsp } from "../worker/security-headers.ts";

const websiteRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const menuPages = ["index.html", "en.html", "ru.html"];

/**
 * Every inline `<script>` in the built menu, as a CSP source expression.
 *
 * Computed rather than pinned: the menu's inline script is generated, and a
 * hand-written hash would silently blank the search box and the scroll-spy the
 * first time anyone edited it.
 */
async function collectMenuScriptHashes() {
  const hashes = new Set();
  for (const page of menuPages) {
    const html = await readFile(join(websiteRoot, "public", "menu", page), "utf8");
    const inline = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)];
    if (inline.length === 0) {
      throw new Error(`${page}: expected an inline script to hash — did the menu build change?`);
    }
    for (const [, body] of inline) {
      hashes.add(`sha256-${createHash("sha256").update(body, "utf8").digest("base64")}`);
    }
  }
  return [...hashes];
}

const rule = (path, headers) =>
  [path, ...Object.entries(headers).map(([name, value]) => `  ${name}: ${value}`), ""].join("\n");

const menuHashes = await collectMenuScriptHashes();

// The Worker needs these too. Locally — and possibly in production, depending
// on whether static assets bypass the Worker — `_headers` is never consulted,
// so the Worker must be able to serve the strict menu CSP itself. Emitting a
// module keeps the hashes in exactly one place: this script.
await writeFile(
  join(websiteRoot, "worker", "menu-script-hashes.generated.ts"),
  [
    "// Generated by scripts/write-headers.mjs — do not edit by hand.",
    "// SHA-256 of every inline <script> in the built menu pages.",
    "export const MENU_SCRIPT_HASHES = [",
    ...menuHashes.map((hash) => `  ${JSON.stringify(hash)},`),
    "] as const;",
    "",
  ].join("\n"),
  "utf8",
);

const content = [
  "# Generated by scripts/write-headers.mjs — do not edit by hand.",
  "# Applies to statically served assets only. The rendered pages get their",
  "# headers from worker/index.ts; both read worker/security-headers.ts.",
  "",
  rule("/*", { ...BASELINE_HEADERS }),
  // The menu is static HTML with hashed inline scripts, so it needs no
  // 'unsafe-inline' the way the RSC-streamed pages do.
  rule("/menu/*", { "Content-Security-Policy": menuCsp(menuHashes) }),
  // vinext writes this rule itself, but only when no _headers file exists.
  rule("/assets/*", { "Cache-Control": "public, max-age=31536000, immutable" }),
  rule("/fonts/*", { "Cache-Control": "public, max-age=31536000, immutable" }),
  rule("/menu/assets/fonts/*", { "Cache-Control": "public, max-age=31536000, immutable" }),
].join("\n");

await writeFile(join(websiteRoot, "public", "_headers"), content, "utf8");

console.log(`Wrote public/_headers (menu CSP pins ${menuHashes.length} inline script hashes).`);
