// Generated by scripts/write-headers.mjs — do not edit by hand.
// SHA-256 of every inline <script> in the built menu pages.
export const MENU_SCRIPT_HASHES = [
  "sha256-fB+YUKUXPyoHGhIjdkxy2TPpYmxq5Hlo4W6Msv8uHhI=",
  "sha256-XoR7g0fzxX6Da3EeD3W7lSBATeygW6XEu9hsWJ84PJA=",
  "sha256-7bH3bAF+cmrntE1BYToS3SAgJ+nfGsZCvX+Ma8SVeCg=",
] as const;
