/**
 * Security headers, shared by the two delivery paths.
 *
 * Cloudflare serves this project from two places and only one of them reads
 * `public/_headers`:
 *
 *  - **Static assets** (`/menu/*`, `/assets/*`, `/images/*`, `/fonts/*`) are
 *    served by Workers Static Assets, which applies `_headers`. That file is
 *    generated by `scripts/write-headers.mjs` from the values below.
 *  - **The rendered pages** (`/`, `/en`, `/ru`) come out of the Worker, which
 *    `_headers` never touches. `worker/index.ts` applies them itself.
 *
 * Keeping both in one module is what stops the two paths from drifting.
 *
 * This module stays free of generated imports on purpose: `write-headers.mjs`
 * imports it to build `_headers`, so importing the generated hashes back into
 * it would be a cycle. Callers pass the hashes in.
 */

/** Headers every response gets, whichever path served it. */
export const BASELINE_HEADERS: Record<string, string> = {
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  // No preload: that submission is effectively irreversible for the domain.
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "Permissions-Policy":
    "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()",
  "Cross-Origin-Opener-Policy": "same-origin",
  "X-Frame-Options": "DENY",
};

const SHARED_CSP = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  // CSS backgrounds in the menu are inline SVG data: URIs.
  "img-src 'self' data:",
  "font-src 'self'",
  "style-src 'self'",
  "upgrade-insecure-requests",
];

/**
 * CSP for the server-rendered pages.
 *
 * `script-src` has to allow inline scripts: vinext streams the RSC payload as
 * ~16 inline `<script>` blocks whose contents change on every build, and it
 * exposes no nonce or hash hook. Everything else stays locked down, so this
 * still blocks framing, base-tag hijacking, plugin content, foreign script
 * origins and off-origin form posts. Drop `'unsafe-inline'` the moment vinext
 * grows nonce support.
 */
export const APP_CSP = [
  ...SHARED_CSP,
  "script-src 'self' 'unsafe-inline'",
  "connect-src 'self'",
  "form-action 'self'",
].join("; ");

/**
 * CSP for the standalone menu, which is plain static HTML with exactly one
 * inline script per page. Those are hashed at build time, so the menu needs no
 * `'unsafe-inline'` at all — and it has no forms and talks to nothing.
 */
export function menuCsp(scriptHashes: readonly string[]): string {
  return [
    ...SHARED_CSP,
    `script-src ${scriptHashes.map((hash) => `'${hash}'`).join(" ")}`,
    "connect-src 'none'",
    "form-action 'none'",
  ].join("; ");
}

/**
 * Apply the baseline plus the right CSP for this path.
 *
 * The Worker sets the menu policy too, rather than leaving it to `_headers`:
 * whether static assets bypass the Worker depends on deployment configuration,
 * and when they do not, `_headers` is never consulted. Doing it here means the
 * menu keeps its strict, hash-pinned policy either way.
 */
export function withSecurityHeaders(
  request: Request,
  response: Response,
  menuScriptHashes: readonly string[],
): Response {
  // Copy onto a fresh Response rather than mutating: the SSR body is a stream
  // and its headers are immutable.
  const headers = new Headers(response.headers);
  for (const [name, value] of Object.entries(BASELINE_HEADERS)) {
    headers.set(name, value);
  }
  const isMenu = new URL(request.url).pathname.startsWith("/menu/");
  headers.set("Content-Security-Policy", isMenu ? menuCsp(menuScriptHashes) : APP_CSP);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
